### ISSUE TITLE
Firefox not installing on Debian

### ISSUE THREAD

**Issue by gggeek** [dhoer/chef-selenium_grid#1]
Is it just me, or support for setting up Firefox is just commented out in the code?
If so, should it be documented?

I ask because I set up a Selenium hub on a vm based on Debian 8, and I only get Chorme available...

**Comment by dhoer** [comment]
I think that should have been supported.  Let me verify mozilla_firefox cookbook is working with Debian 8.  If it is, I will fix this. Thanks

**Comment by dhoer** [comment]
Did you have trouble with xvfb on Debian 8?   I can't seem to get past this issue: https://travis-ci.org/dhoer/chef-selenium_grid/jobs/114316382#L1108

**Comment by gggeek** [comment]
tbh I spent a couple of hours today substituting xvfb with tightvnc (in my cookbook, just after setting up selenium using the selenium_grid recipe).

I prefer using vnc as it allows the developers to connect at any time and see what the browser is actually doing, which helps with debugging selenium scripts
