### ISSUE TITLE
undefined method `domain' for Custom resource windows_autologin from cookbook windows_autologin

### ISSUE THREAD

**Issue by chris-orchard** [dhoer/chef-selenium_grid#2]
I have been getting the following error since the weekend when trying to provision on Windows.

`undefined method 'domain' for Custom resource windows_autologin from cookbook windows_autologin`

This seems to be a dependency issue as we are running with the following cookbook versions:
- selenium (3.7.4)
- selenium_grid (1.2.2)
- windows_autologin (3.0.0)
- windows_screenresolution (1.1.0)

`domain` which was present in https://github.com/dhoer/chef-windows_autologin/blob/v2.2.0/resources/default.rb
is no longer there in 3.0: https://github.com/dhoer/chef-windows_autologin/blob/v3.0.0/resources/default.rb

Our cookbook just uses **selenium_grid** and provides some extra output and specifies attributes, so all dependencies come via **selenium_grid**.

Adding a dependency to `'windows_autologin', '~> 2.0'` in my `metadata.rb` works round this issue but I think you either need to:
- make a new release of **windows_screenresolution** which is compatible with **windows_autologin 3.0.0**, 
- or change the dependency in `windows_screenresolution/metadata.rb` to use a pessimistic version constraint of `'windows_autologin', '~> 2.0'`

**Comment by chris-orchard** [comment]
I see you have released **windows_screenresolution 2.0** which has `depends on 'windows_autologin', '>= 3.0'` however the current release of **selenium_grid** still has `depends 'windows_screenresolution', '~> 1.0'` so still has the above issue.

**Comment by dhoer** [comment]
This cookbook requires some TLC.  I will try to get a release out the drops support for chef 11 and opera.

**Comment by chris-orchard** [comment]
Thanks for the quick response. How about a quick fix to **windows_screenresolution**, putting out a 1.1.1 release with `'windows_autologin', '~> 2.0'` in the metadata.rb?

I think that would allow everything else to work as it is until you have time to look at giving this cookbook the TLC.

I'm not sure how much it takes for you to test and release but this one line fix seems like a better workaround in the short term than me (and anyone else trying to use it on Windows) having to put an unused dependency in my metadata.rb (which I've since discovered is causing me Chefspec errors due `Berkshelf::NoSolutionError:
  Unable to satisfy constraints`)

**Comment by dhoer** [comment]
I released windows_screenresolution 1.1.1 as requested

**Comment by dhoer** [comment]
Would adding this constraint to selenium_grid work

**Comment by chris-orchard** [comment]
Thanks that fixes the issue for me. Although Berks still seems to be fetching *windows_screenresolution* 1.1.0 so I've had to put 1.1.1 in my Berksfile to work round that, possibly a Berks bug.
